micronaut:
  application:
    name: data
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
    show-sql: true
jackson:
  serialization:
    writeDatesAsTimestamps: false
jpa.default.properties.hibernate.hbm2ddl.auto: update
